//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Behlog.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BehlogIdentityErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BehlogIdentityErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Behlog.Web.Resources.BehlogIdentityErrors", typeof(BehlogIdentityErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two factor authentication is required for sign-in..
        /// </summary>
        public static string signin_2factor_required {
            get {
                return ResourceManager.GetString("signin.2factor.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه خود را وارد کنید.
        /// </summary>
        public static string signin_password_req {
            get {
                return ResourceManager.GetString("signin.password.req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری خود را وارد کنید.
        /// </summary>
        public static string signin_username_req {
            get {
                return ResourceManager.GetString("signin.username.req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is blocked.
        /// </summary>
        public static string user_status_blocked {
            get {
                return ResourceManager.GetString("user.status.blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was deleted..
        /// </summary>
        public static string user_status_deleted {
            get {
                return ResourceManager.GetString("user.status.deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User status is not valid.
        /// </summary>
        public static string user_status_invalid {
            get {
                return ResourceManager.GetString("user.status.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is locked.
        /// </summary>
        public static string user_status_locked {
            get {
                return ResourceManager.GetString("user.status.locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is disabled..
        /// </summary>
        public static string user_status_not_enabled {
            get {
                return ResourceManager.GetString("user.status.not.enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is invalid.
        /// </summary>
        public static string username_invalid {
            get {
                return ResourceManager.GetString("username.invalid", resourceCulture);
            }
        }
    }
}
